version: "3"
services:
  dogwalker:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: local/dogwalker:latest
    container_name: dogwalker
    volumes:
      - ${DATA_DIR}:/mnt
    ports:
      - ${PORT}:443
    restart: unless-stopped